name: 'Issue Importer'
description: 'Import issues from CSV or JSON files into a GitHub repository'
author: 'https://github.com/dsanchezcr'
branding:
  icon: 'upload'
  color: 'blue'

inputs:
  file-path:
    description: 'Path to the CSV or JSON file containing issues to import'
    required: true
  file-format:
    description: 'Format of the input file (csv or json)'
    required: true
    default: 'csv'
  github-token:
    description: 'GitHub token with repository write permissions'
    required: true
  dry-run:
    description: 'Perform a dry run without creating actual issues'
    required: false
    default: 'false'

outputs:
  issues-created:
    description: 'Number of issues successfully created'
  issues-failed:
    description: 'Number of issues that failed to create'
  summary:
    description: 'Summary of the import operation'

runs:
  using: 'node20'
  main: 'dist/index.js'